### ISSUE TITLE
how to add search feather to this repo

### ISSUE THREAD

**Issue by tiwentichat** [Charca/astro-blog-template#12]
Dear Maxi,

This repo is really great!

But would you like to kindly show a direction on how to add the search feather to this great repo?
New to Astro, I failed to find the guide in official doc of Astro 4.0 T T,

**Comment by rayBlock** [comment]
what is a search feather ?

**Comment by Petemir** [comment]
Maybe he meant feature

**Comment by tiwentichat** [comment]
> Maybe he meant feature

 - -！ yes, it's feature, not feather

**Comment by Charca** [comment]
Hey @tiwentichat, sorry for the super late reply!

I haven't implemented search for Astro sites before, but the two options that come to mind and that I would look into are:

- A third-party service like Algolia (that's what the official Astro docs use for search, for example.)
- Roll your own search using a library like fuse.js. This video tutorial explains how to do it: https://www.youtube.com/watch?v=XnV_2MWqAhQ

**Comment by tiwentichat** [comment]
> Hey @tiwentichat, sorry for the super late reply!
> 
> I haven't implemented search for Astro sites before, but the two options that come to mind and that I would look into are:
> 
> * A third-party service like Algolia (that's what the official Astro docs use for search, for example.)
> * Roll your own search using a library like fuse.js. This video tutorial explains how to do it: https://www.youtube.com/watch?v=XnV_2MWqAhQ

Great! Thank you so much for your reply and solutions!
I would try them.
The style of your blog is cute and I like it very much : )
Have a nice day!
