### ISSUE TITLE
Conflict with astro extends tsconfig 

### ISSUE THREAD

**Issue by fokusferit** [Charca/astro-blog-template#4]
Hey @Charca,

so I'm trying to setup some Blog using your template and when using the astro create agent, it recommends to install "Typescript (strict)".

Doing that adds the following to the tsconfig file:

```
  "extends": "astro/tsconfigs/strict"
```

Somehow this isn't working. It might be me, but I followed only that one command you provided. When I run `npm run build` it fails:

```
[vite:esbuild] failed to resolve "extends":"astro/tsconfigs/strict" in /Users/fTopcu/Desktop/Projects/Personal/ferit-dot-dev/tsconfig.json
file: /Users/fTopcu/Desktop/Projects/Personal/ferit-dot-dev/src/utils/getPostData.ts
 error   failed to resolve "extends":"astro/tsconfigs/strict" in /Users/fTopcu/Desktop/Projects/Personal/ferit-dot-dev/tsconfig.json
  File:
    /Users/fTopcu/Desktop/Projects/Personal/ferit-dot-dev/src/utils/getPostData.ts
```

Maybe you have a hint.

**Comment by antoniwan** [comment]
I have the same issue with a freshly created project.

```
  211  npm init astro -- --template Charca/astro-blog-template
  212  cd arodus-astro-charca
  213  npm run dev
```

I hope this is helpful.

**Comment by badkamyk** [comment]
To make it work, I've simply created a lacking tsconfigs directory and strict.json file inside (astro/tsconfigs/strict.json) on my own.  It seems to work for now. Based on the TS rules you've chosen during project creation, you need to paste one of the following options from official source: https://github.com/withastro/astro/tree/main/packages/astro/tsconfigs into strict.json file. Here's my strict.json example 

```
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "extends": "./base.json",
  "compilerOptions": {
    "strict": true,
    "importsNotUsedAsValues": "error"
  }
}
```

**Comment by aniketpanjwani** [comment]
Confirming the same problem. Removing the "extends" line in tsconfig allows the build to complete.

**Comment by NickSeagull** [comment]
### A solution that worked for me

Update your dependencies with

```bash
npx npm-check-updates -u
npm install
```

**Comment by michaelnguyen238** [comment]
Nick's solution worked for me as well. I had to close my terminal and reopen it to get it to work, didn't catch why that fixed it but it is what it is.

**Comment by m-godyn** [comment]
Also had the problem, also @NickSeagull's solution worked.
